### ISSUE TITLE
#5 Open dialog crash application in case of opening unvailable disk.

### ISSUE THREAD

**Issue by FlaviusHouk** [FlaviusHouk/TagEditor#16]
Application crashes in attemptning to open F:\\(CD-ROM partition in my case).

There have to be more elegant way to determinate user partitions.

**Comment by danyil-hryhoriev** [comment]
Fixed with [commit](https://github.com/FlaviusHouk/TagEditor/commit/bd37ebab1003f1df622e0c3e801662e9b68d580f)

**Comment by FlaviusHouk** [comment]
Still crashing in case of opening unavailable drive.
System returns strange "E://" drive which is not exists in Windows Explorer. Please check it.

**Comment by FlaviusHouk** [comment]
Fixed with [fbbca51](fbbca51ee229661fe9650138a309ebe5d8bdc8b1).
